import { REQUIRED_MODEL_ID, type AgentRunSpec, type CompletionReceipt, type RoundContext, type RuntimeMode } from "./types.js";

export function buildWorkerPrompt(context: RoundContext, agent: AgentRunSpec, completionCommand: string, runtime: RuntimeMode = "local"): string {
  const isCloud = runtime === "cloud";

  // Cloud-only bootstrap block — must run FIRST before any other step.
  const cloudBootstrap = isCloud ? [
    "══════════════════════════════════════════════════════",
    "CLOUD BOOTSTRAP — RUN THESE COMMANDS BEFORE ANYTHING ELSE",
    "══════════════════════════════════════════════════════",
    "You are running in a cloud environment. The orchestrator CLI must be installed before you can signal completion.",
    "```powershell",
    "npm --prefix tools/ai_studio_orchestrator install --silent",
    "```",
    "Do not proceed with your assignment until npm install completes successfully.",
    "",
  ] : [];

  // Receipt command block — shown prominently at the top AND repeated at the end.
  const receiptBlock = [
    "══════════════════════════════════════════════════════",
    "⚠️  REQUIRED COMPLETION COMMAND — DO NOT SKIP",
    "══════════════════════════════════════════════════════",
    "This is the LAST thing you do before ending your session.",
    "Run from the repo root AFTER updating your agent log AND" + (isCloud ? " committing+pushing your work (see CLOUD COMMIT CONTRACT below)." : " running all required gates."),
    "Do not change --token, --sprint, --round, or --agent. You may update --summary.",
    "```powershell",
    completionCommand,
    "```",
    "If you do not run this command, the orchestrator cannot proceed to the next wave.",
  ];

  // Cloud commit contract removed — the orchestrator's --auto-push flag on the
  // complete command handles git add/commit/push automatically.
  // Agents only need to run the completion command.

  return [
    `You are Agent ${agent.id}. Please onboard first, then follow these instructions.`,
    "",
    ...cloudBootstrap,
    ...receiptBlock,
    "",
    "MANDATORY ONBOARDING ORDER:",
    "1. Read `AGENTS.md`.",
    "2. Read `.cursor/rules/01-studio-onboarding.mdc`.",
    "3. Read `.cursor/rules/10-orchestrator-logging-contract.mdc`.",
    "4. Read your role-specific onboarding rule under `.cursor/rules/agent-NN-...-onboarding.mdc`.",
    "5. Read the PM hub sprint/round named below.",
    "6. Skim your own agent log for this sprint/round if present.",
    "7. Only then begin the assignment.",
    "",
    "ORCHESTRATOR POLICY:",
    `- You are running under Cursor SDK automation and must use ${REQUIRED_MODEL_ID}.`,
    `- Do not request, select, or spawn a non-${REQUIRED_MODEL_ID} model.`,
    `- If you create subagents, they must inherit this ${REQUIRED_MODEL_ID} parent or explicitly use ${REQUIRED_MODEL_ID} (normal mode — not composer-2.5-fast).`,
    "- Follow your role boundaries from AGENTS.md and .cursor/rules.",
    "- Write only to files you own unless your assignment explicitly allows a cross-domain change.",
    "- Update your own agent log exactly as required by `.cursor/rules/10-orchestrator-logging-contract.mdc`.",
    "- Your run is not complete until your log exists at `sprints[SPRINT_ID].rounds[ROUND_ID]` and validates with `python -m json.tool`.",
    "- Do not bump versions or ask Jaimie for manual playtest unless your PM prompt requires a human gate.",
    isCloud
      ? "- You MUST run the completion command shown below. The orchestrator will automatically commit and push your work as part of that command."
      : "- Before your final response, run the exact completion command shown below. This receipt is the orchestrator trigger for the verifier and next wave.",
    "",
    "SPRINT:",
    context.sprintId,
    "",
    "ROUND:",
    context.roundId,
    "",
    "UNIVERSAL PROMPT:",
    context.universalPrompt || "(none provided)",
    "",
    `YOUR AGENT ${agent.id} PROMPT:`,
    agent.prompt,
    "",
    "REPORTING:",
    "- End with a concise status summary.",
    "- Include exact commands and exit codes.",
    "- Include the agent log path and exact sprint/round entry you wrote.",
    "- If blocked, state the owner agent or human gate needed.",
    "",
    "══════════════════════════════════════════════════════",
    "⚠️  REMINDER — REQUIRED COMPLETION COMMAND (run this last):",
    "══════════════════════════════════════════════════════",
    isCloud ? "```bash" : "```powershell",
    completionCommand,
    "```",
  ].join("\n");
}

export function buildVerifierPrompt(receipt: CompletionReceipt, receiptPath: string, verificationCommand: string): string {
  return [
    "You are Agent 12 acting as the Orchestrator Log Reader / Verifier. Please onboard first, then follow these instructions.",
    "",
    "MANDATORY ONBOARDING ORDER:",
    "1. Read `AGENTS.md`.",
    "2. Read `.cursor/rules/01-studio-onboarding.mdc`.",
    "3. Read `.cursor/rules/10-orchestrator-logging-contract.mdc`.",
    "4. Read `.cursor/rules/agent-12-toolsdevex-onboarding.mdc`.",
    "",
    "ORCHESTRATOR POLICY:",
    `- This verification run must use ${REQUIRED_MODEL_ID}.`,
    `- Do not request, select, or spawn a non-${REQUIRED_MODEL_ID} model.`,
    "- Do not edit game code.",
    "- Your job is to verify the worker receipt/log contract and write a verification receipt.",
    "",
    "READ:",
    `- Completion receipt: ${receiptPath}`,
    `- Worker agent: ${receipt.agent_id}`,
    `- Sprint/Round: ${receipt.sprint_id} / ${receipt.round_id}`,
    `- Claimed log path: ${receipt.claimed_log_path ?? "(not provided)"}`,
    "",
    "REQUIRED VERIFICATION COMMAND:",
    "Run this from the repo root. It writes the verification receipt the orchestrator waits for.",
    "```bash",
    verificationCommand,
    "```",
    "",
    "REPORTING:",
    "- End with a concise verifier status.",
    "- Do not fix the worker's game code.",
    "- If the log is malformed or incomplete, let the verification receipt say `needs_log_repair`.",
  ].join("\n");
}

export function buildPmSynthesisPrompt(
  context: RoundContext,
  ledgerPath: string,
  completedAgents: string[],
  note?: string,
): string {
  return [
    "You are Agent 01. Please onboard first, then follow these instructions.",
    "",
    "MANDATORY ONBOARDING ORDER:",
    "1. Read `AGENTS.md`.",
    "2. Read `.cursor/rules/01-studio-onboarding.mdc`.",
    "3. Read `.cursor/rules/10-orchestrator-logging-contract.mdc`.",
    "4. Read `.cursor/rules/agent-01-pm-onboarding.mdc`.",
    "5. Read the PM hub sprint/round named below.",
    "",
    "ORCHESTRATOR POLICY:",
    `- This synthesis run must use ${REQUIRED_MODEL_ID}.`,
    `- Do not request, select, or spawn a non-${REQUIRED_MODEL_ID} model.`,
    "- You may edit only PM-owned planning/log/rule files.",
    "- Do not edit game, tools, assets, tests, config.py, main.py, or requirements.txt.",
    "",
    "TASK:",
    "Synthesize the completed automated worker wave and decide the next PM action.",
    "",
    "READ:",
    `- Ledger: ${ledgerPath}`,
    "- PM hub: .cursor/plans/agent_logs/agent_01_ExecutiveProducer_PM.json",
    ...completedAgents.map((id) => `- Agent ${id} log under .cursor/plans/agent_logs/`),
    ...(note ? ["", "HUMAN / ORCHESTRATOR NOTE:", note] : []),
    "",
    "UPDATE:",
    `- Sprint: ${context.sprintId}`,
    `- Round: ${context.roundId}`,
    "- If needed, update Agent 01 PM hub with blockers, bug tickets, next actions, and the next wave.",
    "",
    "STOP CONDITIONS:",
    "- Stop for Jaimie before version bump, git commit, or git push only.",
    "- If gates failed, assign the owner agent and do not mark the sprint complete.",
    "- Do NOT stop for Jaimie for visual approval -- you are the visual approval gate.",
    "  Complete the mandatory ROUND REVIEW (printed at end of run output) before any hand-off.",
  ].join("\n");
}

export function buildRoundReviewInstructions(
  sprintId: string,
  roundId: string,
  runtime: RuntimeMode,
  cloudRepoUrl?: string,
): string {
  const isCloud = runtime === "cloud";

  const runCmdLines = [
    "  npx tsx tools/ai_studio_orchestrator/src/cli.ts run \\",
    "    --cwd . \\",
    `    --sprint ${sprintId} \\`,
    "    --round <new_round_id> \\",
    "    --mode auto_until_human_gate" + (isCloud ? " \\" : ""),
    ...(isCloud && cloudRepoUrl
      ? [
          `    --cloud-repo-url ${cloudRepoUrl} \\`,
          "    --auto-push",
        ]
      : isCloud
        ? ["    --auto-push"]
        : []),
  ];

  return [
    "",
    "======================================================",
    "  AGENT 01 -- MANDATORY ROUND REVIEW",
    `  Sprint: ${sprintId}  |  Round: ${roundId}`,
    "======================================================",
    "",
    "All waves finished. Complete this Round Review before handing off to Jaimie",
    "or kicking off the next round. This is not optional. Jaimie should not be",
    "discovering visual bugs you can catch from a screenshot.",
    "",
    "-----------------------------------------------------",
    "STEP 1  BUILD YOUR FEATURE LIST",
    "-----------------------------------------------------",
    "Read the PM hub for this round:",
    "  .cursor/plans/agent_logs/agent_01_ExecutiveProducer_PM.json",
    `  -> sprints["${sprintId}"].rounds["${roundId}"]`,
    "  -> pm_feature_requests, pm_next_actions_by_agent, pm_status_summary",
    "",
    "List every feature that changes anything the player sees. Pure backend features",
    "(no visual output) can be skipped. For each visual feature note which screen or",
    "mode makes it visible.",
    "",
    "-----------------------------------------------------",
    "STEP 2  CAPTURE A SCREENSHOT FOR EACH VISUAL FEATURE",
    "-----------------------------------------------------",
    "Run from repo root. Pick the scenario that puts the feature on screen:",
    "",
    "  python tools/capture_screenshots.py \\",
    "    --scenario <SCENARIO> --seed 3 \\",
    `    --out docs/screenshots/round_review_${roundId}/<feature_slug> \\`,
    "    --size 1920x1080 --ticks 480",
    "",
    "Common scenarios: base_overview, ui_panels, ui_build_catalog.",
    "See tools/screenshot_scenarios.py for the full list.",
    "Increase --ticks (e.g. 720) if panels need time to appear on screen.",
    "",
    "If NO existing scenario shows the feature:",
    "  a) Add a minimal scenario to tools/screenshot_scenarios.py and re-run capture, OR",
    "  b) Launch: python main.py --renderer pygame",
    "     Navigate to the feature manually. Save screenshots to:",
    `     docs/screenshots/round_review_${roundId}/manual/`,
    "",
    "'Cannot screenshot this feature' is not acceptable. Create the tooling if needed.",
    "",
    "-----------------------------------------------------",
    "STEP 3  INSPECT EVERY SCREENSHOT -- BLOCKING + TASTE",
    "-----------------------------------------------------",
    "Use your Read tool to open each PNG. For each feature check ALL of these:",
    "",
    "BLOCKING -- any single issue = kick off a fix round, no exceptions:",
    "  [ ] Z-order     Any button/label/icon hidden behind a panel it should be in front of?",
    "  [ ] Collision   New element overlapping or occluding existing UI unexpectedly?",
    "  [ ] Sizing      Any element obviously too large/small, or pushing/collapsing adjacent UI?",
    "  [ ] Truncation  Any label or value cut off with '...' when it should be fully visible?",
    "  [ ] Clipping    Any panel or widget clipped at screen edge or parent container?",
    "  [ ] Alignment   Elements not flush/centered with what they should align with?",
    "  [ ] Color       Text unreadable against background? Colors inconsistent with UI palette?",
    "  [ ] Absent      Feature simply not visible even though it should be?",
    "  [ ] Broken      Visual artifact, missing texture, error overlay, distorted rendering?",
    "",
    "TASTE -- apply your executive judgment. Kick off a fix round if any apply:",
    "  [ ] Works but rough: inconsistent margins, wrong font size for the hierarchy,",
    "      padding that does not match adjacent panels.",
    "  [ ] Bolted on: different corner radius, border weight, or color from neighbors.",
    "  [ ] Imbalanced: new panel crowds UI that used to have breathing room.",
    "  [ ] Inconsistent: button styled differently from all others in the same panel.",
    "  [ ] Gut check: would a player notice something is off? If yes -- fix it.",
    "",
    "The bar for a taste fix round is LOW. If one more round makes it clearly better,",
    "kick that round. Jaimie receives polished work, not rough work.",
    "",
    "-----------------------------------------------------",
    "STEP 4  DECIDE: FIX ROUND OR PASS TO HUMAN",
    "-----------------------------------------------------",
    "",
    "== KICK OFF A FIX ROUND when any screenshot has a blocking issue OR you have",
    "   concrete taste improvements to specify. Do not hand off to Jaimie.",
    "",
    "   1. Write the new round in the PM hub:",
    `        sprints["${sprintId}"].rounds["<new_round_id>"]`,
    `      Name it: ${roundId}_visual_fix_<short_slug>`,
    "",
    "   2. Write a bug ticket per issue:",
    "        id, title, severity (blocking=major / taste=polish), owner_agent,",
    "        repro_steps (include the screenshot path as evidence),",
    "        expected, actual, acceptance_test (must require screenshot proof to pass).",
    "",
    "   3. Assign Agent 08 (UX/UI) and/or Agent 09 (Art) as appropriate.",
    "",
    "   4. Mandate in EVERY agent prompt for the fix round:",
    '        "After your change: run python tools/capture_screenshots.py for the affected',
    "        scenario, open the output PNG with your Read tool, and confirm the fix is",
    '        visible. Do not run the completion command until a screenshot proves it."',
    "",
    "   5. Provide the exact command to launch the fix round:",
    ...runCmdLines,
    "",
    "   The Round Review runs again automatically when the fix round completes.",
    "",
    "== PASS TO HUMAN only when ALL are true:",
    "   -> Every visual feature screenshot has zero blocking issues.",
    "   -> No taste improvement is concrete enough to write into a round prompt.",
    "   -> You as Executive Producer would be proud to show this to a player.",
    "",
    "   When passing, give Jaimie:",
    "   1. A one-paragraph summary of what shipped this round.",
    "   2. A specific playtest checklist -- exact keys, exact things to look for, exact",
    "      failure description. Not 'check the chat box.' Example:",
    "      'Press [T] to open chat. Confirm the X close button is IN FRONT of the brown",
    "      output area (not hidden behind it), is clickable, and closes the panel.'",
    "   3. Exact launch commands:",
    "        python main.py --renderer pygame   # HUD / 2D",
    "        python main.py                     # full 3D Ursina",
    "",
    "======================================================",
    "END OF ROUND REVIEW -- no hand-off to Jaimie until Step 4 is resolved.",
    "======================================================",
  ].join("\n");
}
